### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by ghost** [knight-ryu12/discordGaming#20]

**Comment by knight-ryu12** [comment]
lolwut

**Comment by ghost** [comment]
So I can speak ;3

**Comment by knight-ryu12** [comment]
lol

**Comment by ghost** [comment]
IRC + Discord is blocked, unless you have iMessage

**Comment by knight-ryu12** [comment]
Why not use Bouncer

**Comment by ghost** [comment]
What's Bouncer?

**Comment by knight-ryu12** [comment]
ZNC. IRC Bouncer.

**Comment by knight-ryu12** [comment]
You can fake port (redirects to another port). and even IP(if used BoundHost)

**Comment by ghost** [comment]
On iPad

**Comment by knight-ryu12** [comment]
noice

**Comment by ghost** [comment]
What can I do atm?

**Comment by knight-ryu12** [comment]
Make Puesudo code.

**Comment by knight-ryu12** [comment]
And think about DungeonGen?

**Comment by ghost** [comment]
I don't know what the Dungeon would like, can you give an example of 1 room?

**Comment by knight-ryu12** [comment]
Room#1 (int num of room)
Events: 
Battle (vs monster)
Tresure (like dropped item)
Trap
Special -
 Left Right Decision
 Object interaction

**Comment by ghost** [comment]
Will it be a MUD then?

**Comment by ghost** [comment]
Room#1
Intro Event 
Tutorial Battle vs training dummy
Treasure - Basic potion
Trap triggers dummer
Left/Right doesn't matter
Attempt to use potion fails, not needed

**Comment by ghost** [comment]
Like that?

**Comment by knight-ryu12** [comment]
Yeah, MUD like

**Comment by ghost** [comment]
Dungeon dungeon = new DungeonBuilder().setDifficulty(Difficulty.EASY).addRoom(new Room(...)); Idek

**Comment by ghost** [comment]
Woo

**Comment by ghost** [comment]
We should make it so people can submit and design their own dungeons

**Comment by knight-ryu12** [comment]
Oh yeah

**Comment by ghost** [comment]
What is happiness?

**Comment by knight-ryu12** [comment]
Happniess is that I can work with ya guys

**Comment by ghost** [comment]
;3

**Comment by knight-ryu12** [comment]
Then I need update DungeonGen todo!
:D

**Comment by ghost** [comment]
When wil you merge master?

**Comment by knight-ryu12** [comment]
I think today.

**Comment by ghost** [comment]
👌🏻

**Comment by ghost** [comment]
Can nearly help

**Comment by ghost** [comment]
2:30 your time

**Comment by knight-ryu12** [comment]
lol
